### ISSUE TITLE
Internal error from sentencepiece

### ISSUE THREAD

**Issue by skbhat** [mbzuai-oryx/groundingLMM#21]
Hi,

I have successfully installed the offline demo as instructed [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/offline_demo.md)

While running the command :

     python app.py --version ./GLaMM-FullScope

I am getting following error:

Traceback (most recent call last):
  File "/mnt/winD/ML/gitProjs/LLVM/groundingLMM/app.py", line 271, in <module>
    tokenizer = setup_tokenizer_and_special_tokens(args)
  File "/mnt/winD/ML/gitProjs/LLVM/groundingLMM/app.py", line 42, in setup_tokenizer_and_special_tokens
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/srikrishna/Install/conda/conda/envs/glamm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 682, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/srikrishna/Install/conda/conda/envs/glamm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1805, in from_pretrained
    return cls._from_pretrained(
  File "/home/srikrishna/Install/conda/conda/envs/glamm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1959, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/srikrishna/Install/conda/conda/envs/glamm/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 71, in __init__
    self.sp_model.Load(vocab_file)
  File "/home/srikrishna/Install/conda/conda/envs/glamm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/srikrishna/Install/conda/conda/envs/glamm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

Thanks in advance for your time.

**Comment by skbhat** [comment]
Sorry for raising this issue.  I forgot to do "git lfs install" before cloning.
