### ISSUE TITLE
Offline demo error

### ISSUE THREAD

**Issue by Roberyan** [mbzuai-oryx/groundingLMM#66]
When running the offline demo as instruction markdown, I find that the code can not always work. 

It may work for some sample, and  would appear such error:
```
Traceback (most recent call last):
  File "/home/user/groundingLMM/gradio-dev/gradio/routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/groundingLMM/gradio-dev/gradio/blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "/home/user/groundingLMM/gradio-dev/gradio/blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/anaconda3/envs/glamm/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/user/anaconda3/envs/glamm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/user/anaconda3/envs/glamm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/user/groundingLMM/app.py", line 253, in inference
    save_img = prepare_mask(input_image, image_np, pred_masks, text_output, color_history)
  File "/home/user/groundingLMM/app.py", line 133, in prepare_mask
    color = random.choice(colors_temp)
  File "/home/user/anaconda3/envs/glamm/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```

Such error would remain even after the next sample is changed to given demo. How does this happen?

**Comment by dohyun1411** [comment]
https://github.com/mbzuai-oryx/groundingLMM/issues/7#issuecomment-1890992129
This works for me
